config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'my_threads#index'
  resources :my_threads do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:email, :password, :remenber_me)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_my_thread
  before_action :set_comments, only:[:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_owner?, only: :edit

  def new
    @comment = @my_thread.comments.new
  end

  def create
    @my_thread.comments.create(comment_params)
    redirect_to my_thread_path(@my_thread)
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to my_thread_path(@my_thread)
  end

  def destroy
    @comment.destroy
    redirect_to my_thread_path(@my_thread)
  end

  private

  def set_my_thread
    @my_thread = MyThread.find(params[:my_thread_id])
  end

  def set_comments
    @comment = @my_thread.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, my_thread_id: @my_thread.id)
  end

  def is_owner?
    redirect_to my_thread_path(@my_thread.id) unless current_user.id == @comment.user_id
  end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only:[:edit, :show, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_owner?, only: :edit
  def index
    @my_threads = MyThread.includes(:comments).all
  end

  def new
    @my_thread = MyThread.new
  end

  def create
    MyThread.create(my_thread_params)
    redirect_to my_threads_path
  end

  def edit
  end

  def show
    @comments = @my_thread.comments
  end

  def update
    @my_thread.update(my_thread_params)
  end

  def destroy
    @my_thread.delete
    redirect_to my_threads_path
  end

  private

  def set_my_thread
    @my_thread = MyThread.find(params[:id])
  end
  def my_thread_params
    params.require(:my_thread).permit(:title, :description).merge(user_id: current_user.id)
  end

  def is_owner?
    redirect_to my_threads_path unless current_user.id == @my_thread.user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/_form.html.erb
<%= form_for ([my_thread, comment]) do |f| %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comments</h2>

<%= render 'form', {my_thread: @my_thread, comment: @comment} %>


<%= link_to 'Back', my_threads_path %>

app/views/comments/new.html.erb
<h2>New Comments</h2>

<%= render 'form', {my_thread: @my_thread, comment: @comment} %>


<%= link_to 'Back', my_threads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_for my_thread do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.submit %>
<% end %>

app/views/my_threads/edit.html.erb
<h2>New Thread</h2>

<%= render 'form', my_thread: @my_thread %>


<%= link_to 'Back', my_threads_path %>

app/views/my_threads/index.html.erb
<h1>My Thread</h1>

<% @my_threads.each do |my_thread| %>
<li>
<span><%= link_to my_thread.title, my_thread_path(my_thread) %></span>
<p><%= my_thread.description%></p>
<% if current_user.id == my_thread.user_id %>
<%= link_to 'Edit', edit_my_thread_path(my_thread) %>
<%= link_to 'Delete', my_thread_path(my_thread), method: :delete %>
<% end %>
</li>
<% end %>

<%= link_to 'New Thread', new_my_thread_path %>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/my_threads/new.html.erb
<h2>New Thread</h2>

<%= render 'form', my_thread: @my_thread %>


<%= link_to 'Back', my_threads_path %>

app/views/my_threads/show.html.erb
<span>
  <h1><%= @my_thread.title %></h1>
  <%= @my_thread.description %>
<span>

<p><strong>Comments</strong><p>
<ul>
  <% @comments.each do |comment| %>
  <li><%= comment.content %>
    <% if current_user.id == comment.user_id %>
    <%= link_to 'Edit', edit_my_thread_comment_path(@my_thread.id, comment.id)%>
    <%= link_to 'Delete', my_thread_comment_path(@my_thread.id, comment.id), method: :delete%>
    <% end %>
  </li>
  <% end %>
</ul>
<%= link_to 'New Comment', new_my_thread_comment_path(@my_thread) %>
<%= link_to 'Back', my_threads_path %>